import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default async function JournalPost({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  
  const title = slug
    .split("-")
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  return (
    <main className="w-full min-h-screen bg-background text-foreground pt-32 pb-24 px-8 md:px-16">
      <article className="max-w-3xl mx-auto flex flex-col gap-12">
        
        {/* Back Link */}
        <Link href="/journal" className="flex items-center gap-2 text-xs uppercase tracking-widest text-muted-foreground hover:text-foreground transition-colors mb-4">
          <ArrowLeft size={16} /> Back to Journal
        </Link>
        
        {/* Post Metadata */}
        <div className="flex flex-col gap-4 border-b border-border/20 pb-8">
          <div className="flex justify-between items-center text-xs text-primary/70 uppercase tracking-widest">
            <span>Journal Entry</span>
            <span className="text-muted-foreground font-mono">Sep 12, 2026</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-light uppercase tracking-tight leading-tight mt-2">
            {title}
          </h1>
        </div>

        {/* Big visual placeholder */}
        <div className="aspect-[16/9] bg-secondary/30 relative flex items-center justify-center rounded-sm">
          <span className="text-muted-foreground/30 font-mono tracking-widest text-xs uppercase">Post Illustration</span>
        </div>

        {/* Narrative / Content */}
        <div className="flex flex-col gap-8 text-lg font-light leading-relaxed text-muted-foreground">
          <p>
            The process begins long before the dye meets the leather. Inside the quiet parameters of our workshop, each shoe acts as a canvas. When calfskin is in its raw crust form, it has a uniform, soft ivory hue. It is pure potential.
          </p>
          <h2 className="text-2xl uppercase tracking-wider text-foreground font-light mt-4">The First Layer</h2>
          <p>
            A colorist applies alcohol-based pigments using cotton daubers, working from light tones to dark. Circular patterns create a textured look, while linear strokes lend speed and direction to the grain. As the solvents evaporate, the pigment bonds with the leather fibers, building a permanent base layer.
          </p>
          <p>
            It requires patience. Applying color too quickly results in saturation and muddy transitions. A proper bespoke patina relies on the space between coats, allowing the leather to breathe and fully cure.
          </p>
          <h2 className="text-2xl uppercase tracking-wider text-foreground font-light mt-4">Burnishing & Waxing</h2>
          <p>
            The signature look is locked in during the burnishing phase. Using custom circular buffers and pure beeswax, the colorist polishes the toe cap, heel, and welts. The heat generated by friction melts the waxes into the pores, creating a brilliant glaze that is highly water-resistant.
          </p>
        </div>

        {/* Author / Signoff */}
        <div className="border-t border-border/20 pt-8 mt-12 flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-secondary border border-border flex items-center justify-center text-xs font-mono">
            N
          </div>
          <div className="flex flex-col">
            <span className="text-sm font-medium uppercase tracking-widest">Nelson Atelier</span>
            <span className="text-xs text-muted-foreground">Master Colorists</span>
          </div>
        </div>

      </article>
    </main>
  );
}
